### ISSUE TITLE
신고 결과 받기

### ISSUE THREAD

**Issue by sbjang123456** [sbjang123456/TIL#34]
프로그래머스 - [신고결과받기](https://programmers.co.kr/learn/courses/30/lessons/92334)

**Comment by sbjang123456** [comment]
_테스트케이스 시간초과..._
```javascript
function solution(id_list, report, k) {
    const set = new Set(report);
    const answer = id_list.map((id) => {
        let i = 0;
        for (let item of set) {
            const [usrId, criminalId] = item.split(' ');
            if ([...set].filter(x => x.split(' ')[1] === criminalId).length >= k) {
                if (usrId === id) {
                    i++;
                }
            }
        }
        return i;
    });
    
    return answer;
}
```

**Comment by sbjang123456** [comment]
filter 때문인가 싶어서 밖에서 미리 가공 후 비교했는데도 시간초과~ ㅠ..ㅠ
```js
function solution(id_list, report, k) {
    let answer = [];

    const sets = new Set(report);
    const reportedMap  = new Map();
    for (const set of sets) {
        const [reporter, reported] = set.split(' ');
        reportedMap.set(reported, (reportedMap.get(reported) || 0) + 1);
    }

    answer = id_list.map((id, idx) => {
        let sendMail = 0;
        for (const set of sets) {
            const [reporter, reported] = set.split(' ');
            if (reporter === id && reportedMap.get(reported) >= k) {
                sendMail++;
            }
        }

        return sendMail;
    });

    return answer;
}
```

**Comment by sbjang123456** [comment]
```js
function solution(id_list, report, k) {
    let answer = [];

    const sets = new Set(report);
    const alarms = new Array(id_list.length).fill(0);

    const arrReportedCount = [...alarms];
    for (const set of sets) {
        const [, reported] = set.split(' ');
        arrReportedCount[id_list.indexOf(reported)]++;
    }

    for (const set of sets) {
        const [reporter, reported] = set.split(' ');
        if (arrReportedCount[id_list.indexOf(reported)] >= k) {
            alarms[id_list.indexOf(reporter)]++;
        }
    }
    return alarms;
}

```

**Comment by SooJungChae** [comment]
> filter 때문인가 싶어서 밖에서 미리 가공 후 비교했는데도 시간초과~ ㅠ..ㅠ
> 
> ```js
> function solution(id_list, report, k) {
>     let answer = [];
> 
>     const sets = new Set(report);
>     const reportedMap  = new Map();
>     for (const set of sets) {
>         const [reporter, reported] = set.split(' ');
>         reportedMap.set(reported, (reportedMap.get(reported) || 0) + 1);
>     }
> 
>     answer = id_list.map((id, idx) => {
>         let sendMail = 0;
>         for (const set of sets) {
>             const [reporter, reported] = set.split(' ');
>             if (reporter === id && reportedMap.get(reported) >= k) {
>                 sendMail++;
>             }
>         }
> 
>         return sendMail;
>     });
> 
>     return answer;
> }
> ```

O(2) 라서 그런거겠죠??

**Comment by sbjang123456** [comment]
> > filter 때문인가 싶어서 밖에서 미리 가공 후 비교했는데도 시간초과~ ㅠ..ㅠ
> > ```js
> > function solution(id_list, report, k) {
> >     let answer = [];
> > 
> >     const sets = new Set(report);
> >     const reportedMap  = new Map();
> >     for (const set of sets) {
> >         const [reporter, reported] = set.split(' ');
> >         reportedMap.set(reported, (reportedMap.get(reported) || 0) + 1);
> >     }
> > 
> >     answer = id_list.map((id, idx) => {
> >         let sendMail = 0;
> >         for (const set of sets) {
> >             const [reporter, reported] = set.split(' ');
> >             if (reporter === id && reportedMap.get(reported) >= k) {
> >                 sendMail++;
> >             }
> >         }
> > 
> >         return sendMail;
> >     });
> > 
> >     return answer;
> > }
> > ```
> 
> O(n2) 라서 그런거겠죠??

실패한 저 친구들은 이중 반복 이상을 원치 않는것 같더라구요.
처음부터 문제의 특성에 맞는 자료구조를 생각해내는 연습이 필요할 것 같네요 ㅠ.ㅠ

**Comment by SooJungChae** [comment]
> 처음부터 문제의 특성에 맞는 자료구조를 생각해내는 연습이 필요할 것 같네요 ㅠ.ㅠ

공감합니다..! ㅠㅠ 저도 연습 많이 해야겠어요
