### ISSUE TITLE
IDE vscode 처음셋팅~ 

### ISSUE THREAD

**Issue by sbjang123456** [sbjang123456/TIL#56]

**Comment by SooJungChae** [comment]
Vscode??!!!

**Comment by sbjang123456** [comment]
> Vscode??!!!

이유는 모르겠으나 집에 웹스톰이 너무너뮤너무너무 느려서 집에선 vscode 쓰려고합니다.. ㅠ.ㅠ

**Comment by SooJungChae** [comment]
오 좀 적응되시면 회사에서도 전부 vscode 로 통일해도 좋을거같네여!!
