### ISSUE TITLE
yarn berry 공부해보자!

### ISSUE THREAD

**Issue by sbjang123456** [sbjang123456/TIL#59]
https://toss.tech/article/node-modules-and-yarn-berry 읽어보기!

**Comment by SooJungChae** [comment]
+ nvm 차이??

**Comment by sbjang123456** [comment]
> 플러스 nvm 차이??
> 
> -> 이건 그냥 node 버전 관리용이네요.

넵 맞습니다. nvm 은 노드버전매니저고
yarn berry 는 패키지 매니저라고 보면 될 것 같아요. `npm` , `yarn` 과 비슷한 친구들이죠.
많은 회사들이 채택하고 있다고해서 한번 공부해보려고 합니다.

**Comment by SooJungChae** [comment]
오 좋네요~ 저도 같이 공부해봐야겠어요!

**Comment by hong-brother** [comment]
저도 같이 공부해봐요~ ㅎㅎ
